cxx_test(
    name = "test",
    srcs = [
        "test.cpp",
    ],
    deps = [
        "//boost:boost",
        "//gflags:gflags",
        "//glog:glog",
        "//libevent:libevent",
        "//thrift:thrift",
        "//double-conversion:double-conversion",
        "//jemalloc:jemalloc",
        "//snappy:snappy",
        "//lz4:lz4",
        "//openssl:openssl",
        "//fatal:fatal",
        "//json:json",
    ],
)

cxx_binary(
    name = "po",
    srcs = [
        "po.cpp",
    ],

    deps = [
        "//boost:boost",
    ],
)
