cxx_library(    
    name = "bzip2",
    header_namespace = "",
    srcs = glob([
        "bzip2/*.c",
    ]),
    compiler_flags = [
        "-w",
    ],
    headers = subdir_glob([
        ("bzip2", "*.h"),
    ]),
    exported_headers = subdir_glob([
        ("bzip2", "bzlib.h"),
    ]),

    tests = [
        ":test",
    ],

    visibility = [
        "PUBLIC",
    ],
)

cxx_test(
    name = "test",
    srcs = [
        "test.cpp",
    ],
    deps = [
        "//bzip2:bzip2",
    ],
)
