cxx_library(
    name = "json",
    header_namespace = "json",
    exported_headers = subdir_glob([
        ("json", "**/*.hpp"),
    ]),

    visibility = [
        "PUBLIC",
    ],
)

cxx_test(
    name = "test",
    deps = [
        ":json",
    ],
    srcs = [
        "test.cpp",
    ],
)
